{ ... }:
{
  imports = [
    ./autopairs.nix
    ./crates.nix
    ./autotag.nix
    ./blankline.nix
    ./conform.nix
    ./diffview.nix
    ./flash.nix
    ./flutter-tools.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./lazygit.nix
    ./lsp.nix
    ./lualine.nix
    ./noice.nix
    ./nvim-cmp.nix
    ./oil.nix
    ./rainbow-delimiters.nix
    ./sidekick.nix
    ./smart-splits.nix
    ./sort.nix
    ./surround.nix
    ./telescope.nix
    ./todo.nix
    ./treesitter.nix
    ./trouble.nix
    ./quicker.nix
  ];
}
